require('vis')

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
  vis:command('set autoindent on')
  vis:command('set colorcolumn 80')
  vis:command('set expandtab on')
  vis:command('set number')
  vis:command('set show-spaces on')
  vis:command('set show-tabs on')
  vis:command('set tabwidth 2')
end)
